css-brochure-form | Nick Hernandez
Nickolas-Hernandez/c0121-code-solutions pull request #15
Opened 2021-01-21 01:46 UTC by Nickolas-Hernandez

![Screen Shot 2021-01-20 at 5 45 56 PM](https://user-images.githubusercontent.com/75342275/105268577-5ada6580-5b47-11eb-83f1-e7ab98f02be9.png)

2021-01-21 21:16 UTC, codingcodymiller requested changes
Hey Nick, nice work so far! Please see my notes

2021-01-21 21:16 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +}
This was already applied in `reset.css`, it can be removed.

2021-01-21 21:16 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  width: 24%;
You should do this in `px`

2021-01-21 21:32 UTC, Nickolas-Hernandez commented on css-brochure-form/styles.css
> +  width: 24%;
![Screen Shot 2021-01-21 at 1 31 43 PM](https://user-images.githubusercontent.com/75342275/105414985-0db0cf00-5bed-11eb-9747-d37216029436.png)

Corrections made.

2021-01-23 00:20 UTC, codingcodymiller approved these changes
🥳 🥳 🥳

2021-01-23 00:34 UTC, merged