Css two column layout | Nick Hernandez
Nickolas-Hernandez/c0121-code-solutions pull request #20
Opened 2021-01-22 23:28 UTC by Nickolas-Hernandez

![Screen Shot 2021-01-22 at 3 26 56 PM](https://user-images.githubusercontent.com/75342275/105559516-453f7a00-5cc6-11eb-8650-9b4077fbd933.png)

2021-01-23 03:16 UTC, codingcodymiller requested changes
Nice work so far!! A couple minor changes:

2021-01-23 03:16 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  /* padding: 2rem 0; */
Remove commented code before submitting

2021-01-23 03:16 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
![nice](https://user-images.githubusercontent.com/32880187/105567356-3963b000-5ce6-11eb-9ab2-7d6d66735774.gif)

2021-01-23 03:55 UTC, Nickolas-Hernandez commented on css-two-column-layout/styles.css
> +  /* padding: 2rem 0; */
would this also include an "scaffolding comments" such as noting where global styles are or where certain section styles are?

2021-01-23 04:08 UTC, Nickolas-Hernandez commented on css-two-column-layout/styles.css
> +  /* padding: 2rem 0; */
![Screen Shot 2021-01-22 at 8 07 54 PM](https://user-images.githubusercontent.com/75342275/105568358-8e56f480-5ced-11eb-8500-adbc5037e817.png)

removed commented code

2021-01-27 02:40 UTC, codingcodymiller approved these changes
Nice work!! And to answer your question, comments to label sections are okay, just don't go too far overboard with it. In general, your code should describe itself well enough that comments aren't necessary.

2021-01-27 03:26 UTC, merged